name: CD
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:14.5.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Build
        run: npm run build