name: CI
on:
  push:
    # branches-ignore:
    #   - main
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:14.5.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Linter
        run: npm run lint